<?php
/**
 * PDF Generator for Interview Questions
 *
 * Generates a professional PDF download of interview questions
 * using the FPDF library.
 *
 * @package x0pa-hiring-templates
 */

// Check if FPDF library exists
$fpdf_path = dirname(__DIR__) . '/lib/fpdf/fpdf.php';
if (!file_exists($fpdf_path)) {
    die('FPDF library not found. Please download fpdf.php from http://www.fpdf.org/ and place it in includes/lib/fpdf/');
}

require_once($fpdf_path);

/**
 * Generate interview questions PDF
 *
 * @param string $job_title Job title (e.g., "Accountant")
 * @param array $questions Array of interview questions
 * @param string $filename Output filename (optional)
 * @return void Outputs PDF for download
 */
function generate_interview_questions_pdf($job_title, $questions, $filename = null) {
    // Create PDF instance
    $pdf = new FPDF();
    $pdf->AddPage();

    // Set auto page break
    $pdf->SetAutoPageBreak(true, 20);

    // Colors
    $primary_color = array(23, 59, 140); // #173b8c
    $accent_color = array(245, 158, 10); // #f59e0a
    $dark_color = array(23, 20, 28);     // #17141c
    $gray_color = array(163, 161, 168);  // #a3a1a8

    // Header - x0pa logo text
    $pdf->SetFont('Arial', 'B', 24);
    $pdf->SetTextColor($primary_color[0], $primary_color[1], $primary_color[2]);
    $pdf->Cell(0, 15, 'x0pa', 0, 1, 'L');

    // Subheader
    $pdf->SetFont('Arial', '', 10);
    $pdf->SetTextColor($gray_color[0], $gray_color[1], $gray_color[2]);
    $pdf->Cell(0, 5, 'AI-Powered Hiring Intelligence', 0, 1, 'L');
    $pdf->Ln(5);

    // Horizontal line
    $pdf->SetDrawColor($gray_color[0], $gray_color[1], $gray_color[2]);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(10);

    // Title
    $pdf->SetFont('Arial', 'B', 18);
    $pdf->SetTextColor($dark_color[0], $dark_color[1], $dark_color[2]);
    $question_count = count($questions);
    $pdf->MultiCell(0, 10, $question_count . ' ' . $job_title . ' Interview Questions', 0, 'L');
    $pdf->Ln(5);

    // Description
    $pdf->SetFont('Arial', '', 11);
    $pdf->SetTextColor($gray_color[0], $gray_color[1], $gray_color[2]);
    $pdf->MultiCell(0, 6, 'Use these expert-crafted interview questions to evaluate ' . strtolower($job_title) . ' candidates effectively and make data-driven hiring decisions.', 0, 'L');
    $pdf->Ln(8);

    // Questions list
    $pdf->SetFont('Arial', '', 11);
    $pdf->SetTextColor($dark_color[0], $dark_color[1], $dark_color[2]);

    foreach ($questions as $index => $question) {
        $question_number = $index + 1;

        // Check if we need a new page
        if ($pdf->GetY() > 250) {
            $pdf->AddPage();
        }

        // Question number (bold, accent color)
        $pdf->SetFont('Arial', 'B', 11);
        $pdf->SetTextColor($accent_color[0], $accent_color[1], $accent_color[2]);
        $pdf->Cell(10, 7, $question_number . '.', 0, 0, 'R');

        // Question text
        $pdf->SetFont('Arial', '', 11);
        $pdf->SetTextColor($dark_color[0], $dark_color[1], $dark_color[2]);
        $pdf->MultiCell(0, 7, ' ' . $question, 0, 'L');
        $pdf->Ln(3);
    }

    // Footer section
    $pdf->Ln(10);
    $pdf->SetDrawColor($gray_color[0], $gray_color[1], $gray_color[2]);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(5);

    $pdf->SetFont('Arial', 'I', 9);
    $pdf->SetTextColor($gray_color[0], $gray_color[1], $gray_color[2]);
    $pdf->MultiCell(0, 5, 'Generated by X0PA AI', 0, 'C');

    // Add clickable link with tracking parameter (centered)
    $pdf->SetTextColor($primary_color[0], $primary_color[1], $primary_color[2]);
    $link_text = 'Visit us at https://x0pa.com';
    $link_width = $pdf->GetStringWidth($link_text);
    $pdf->SetX((210 - $link_width) / 2);  // Center on A4 page (210mm width)
    $pdf->Write(5, $link_text, 'https://x0pa.com/?source=interview-questions-pdf');
    $pdf->Ln();

    // Output PDF
    if ($filename === null) {
        $filename = strtolower(str_replace(' ', '-', $job_title)) . '-interview-questions-x0pa.pdf';
    }

    $pdf->Output('D', $filename);
}

/**
 * Generate job description PDF
 *
 * @param string $job_title Job title (e.g., "Accountant")
 * @param array $content_sections Array of content sections with titles and content
 * @param string $filename Output filename (optional)
 * @return void Outputs PDF for download
 */
function generate_job_description_pdf($job_title, $content_sections, $filename = null) {
    // Create PDF instance
    $pdf = new FPDF();
    $pdf->AddPage();

    // Set auto page break
    $pdf->SetAutoPageBreak(true, 20);

    // Colors
    $primary_color = array(23, 59, 140); // #173b8c
    $accent_color = array(245, 158, 10); // #f59e0a
    $dark_color = array(23, 20, 28);     // #17141c
    $gray_color = array(163, 161, 168);  // #a3a1a8

    // Header - x0pa logo text
    $pdf->SetFont('Arial', 'B', 24);
    $pdf->SetTextColor($primary_color[0], $primary_color[1], $primary_color[2]);
    $pdf->Cell(0, 15, 'x0pa', 0, 1, 'L');

    // Subheader
    $pdf->SetFont('Arial', '', 10);
    $pdf->SetTextColor($gray_color[0], $gray_color[1], $gray_color[2]);
    $pdf->Cell(0, 5, 'AI-Powered Hiring Intelligence', 0, 1, 'L');
    $pdf->Ln(5);

    // Horizontal line
    $pdf->SetDrawColor($gray_color[0], $gray_color[1], $gray_color[2]);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(10);

    // Title
    $pdf->SetFont('Arial', 'B', 18);
    $pdf->SetTextColor($dark_color[0], $dark_color[1], $dark_color[2]);
    $pdf->MultiCell(0, 10, $job_title . ' Job Description', 0, 'L');
    $pdf->Ln(8);

    // Content sections
    foreach ($content_sections as $section) {
        // Check if we need a new page
        if ($pdf->GetY() > 240) {
            $pdf->AddPage();
        }

        // Section title
        $pdf->SetFont('Arial', 'B', 13);
        $pdf->SetTextColor($primary_color[0], $primary_color[1], $primary_color[2]);
        $pdf->MultiCell(0, 7, $section['title'], 0, 'L');
        $pdf->Ln(3);

        // Section content
        $pdf->SetFont('Arial', '', 11);
        $pdf->SetTextColor($dark_color[0], $dark_color[1], $dark_color[2]);
        $pdf->MultiCell(0, 6, $section['content'], 0, 'L');
        $pdf->Ln(6);
    }

    // Footer section
    $pdf->Ln(5);
    $pdf->SetDrawColor($gray_color[0], $gray_color[1], $gray_color[2]);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(5);

    $pdf->SetFont('Arial', 'I', 9);
    $pdf->SetTextColor($gray_color[0], $gray_color[1], $gray_color[2]);
    $pdf->MultiCell(0, 5, 'Generated by X0PA AI', 0, 'C');

    // Add clickable link with tracking parameter (centered)
    $pdf->SetTextColor($primary_color[0], $primary_color[1], $primary_color[2]);
    $link_text = 'Visit us at https://x0pa.com';
    $link_width = $pdf->GetStringWidth($link_text);
    $pdf->SetX((210 - $link_width) / 2);  // Center on A4 page (210mm width)
    $pdf->Write(5, $link_text, 'https://x0pa.com/?source=job-description-pdf');
    $pdf->Ln();

    // Output PDF
    if ($filename === null) {
        $filename = strtolower(str_replace(' ', '-', $job_title)) . '-job-description.pdf';
    }

    $pdf->Output('D', $filename);
}
?>
